// These types mirror the OpenAPI spec generated by the backend.
// In practice they are imported from @odyssey/api-client (Orval-generated).
// This package holds supplementary hand-authored types that extend generated ones.

export type OrderStatus =
  | 'pending'
  | 'confirmed'
  | 'preparing'
  | 'ready'
  | 'completed'
  | 'cancelled';

export type OrderAction =
  | 'confirm'
  | 'start_preparing'
  | 'mark_ready'
  | 'complete'
  | 'cancel';

export interface MenuCategory {
  id: number;
  name: string;
  description: string | null;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
}

export interface MenuItem {
  id: number;
  categoryId: number;
  name: string;
  description: string | null;
  /** Price in cents */
  price: number;
  available: boolean;
  prepTimeMinutes: number;
  imageUrl: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Customer {
  id: number;
  name: string;
  email: string | null;
  phone: string | null;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface CustomerSummary extends Customer {
  orderCount: number;
  totalSpend: number;
}

export interface OrderItem {
  id: number;
  orderId: number;
  menuItemId: number;
  quantity: number;
  unitPrice: number;
  subtotal: number;
  menuItem?: MenuItem;
}

export interface Order {
  id: number;
  customerId: number | null;
  status: OrderStatus;
  /** Subtotal in cents */
  subtotal: number;
  /** Total in cents */
  total: number;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
  items?: OrderItem[];
  customer?: Customer | null;
}

export interface Setting {
  id: number;
  key: string;
  value: string;
  updatedAt: string;
}

export interface DashboardSummary {
  totalOrders: number;
  totalRevenue: number;
  pendingOrders: number;
  confirmedOrders: number;
  preparingOrders: number;
  completedOrdersToday: number;
  revenueToday: number;
  popularItems: Array<{ menuItemId: number; name: string; orderCount: number }>;
}

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
}

export interface ApiError {
  error: string;
  details?: unknown;
}
